
set nu
set hlsearch 
set showmatch
set bg=dark
vmap ,mc !boxes -d c-cmt<CR>
nmap ,mc !!boxes -d c-cmt<CR>
vmap ,xc !boxes -d c-cmt -r<CR>
nmap ,xc !!boxes -d c-cmt -r<CR>
vmap ,dc !boxes -d dog <CR>
vmap ,nd !boxes -d dog -r<CR>

"viFu 
"
nmap <leader>w :w!<cr>
nmap <leader>ww :wq!<cr>
nmap <leader>q :q!<cr>

" Tab configuration
map <leader>tn :tabnew<cr>
map <leader>te :tabedit
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove
